name: KTB Image Crawler

on:
  repository_dispatch:
    types: [new_product_available]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 python-telegram-bot

      - name: Run crawler
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python crawler-image.py

      - name: Send Log Content to Telegram
        if: always()
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          LOG_CONTENT=$(cat crawl-log.txt)
          TRUNCATED_LOG=$(echo "$LOG_CONTENT" | head -c 4000)
          curl -s -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage \
          -d chat_id=$TELEGRAM_CHAT_ID \
          -d text="${TRUNCATED_LOG}" || echo "Lỗi khi gửi nội dung log!"

      - name: Check for changes
        id: check_changes
        run: |
          git add *.txt
          if ! git diff --staged --quiet; then
            echo "Có thay đổi, tiến hành commit và trigger."
            echo "changes_exist=true" >> "$GITHUB_OUTPUT"
          else
            echo "Không có thay đổi nào."
            echo "changes_exist=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Commit & push results
        if: success() && steps.check_changes.outputs.changes_exist == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "Update URLs [skip ci]"
          git push

      # ----- BƯỚC KÍCH HOẠT ĐÃ ĐƯỢC THAY THẾ -----
      - name: Check status and trigger generator workflow
        if: success() && steps.check_changes.outputs.changes_exist == 'true'
        id: trigger_generator # Đặt ID để lấy output cho Telegram
        env:
          GH_TOKEN: ${{ secrets.KTBHUB_PAT }} # Sử dụng PAT cho repo ktb-image
          TARGET_OWNER: 'ktbhub'
          TARGET_REPO: 'ktb-image'
          TARGET_WORKFLOW: 'auto-generate.yml' # <-- THAY TÊN FILE WORKFLOW CỦA REPO ĐÍCH
        run: |
          echo "Checking status of '${TARGET_WORKFLOW}' in ${TARGET_OWNER}/${TARGET_REPO}..."

          in_progress_runs=$(gh run list \
            --repo "${TARGET_OWNER}/${TARGET_REPO}" \
            --workflow "${TARGET_WORKFLOW}" \
            --status "in_progress" \
            --status "queued" \
            --limit 1 \
            --json databaseId)

          if [[ "$in_progress_runs" != "[]" ]]; then
            echo "Generator workflow is busy. Skipping trigger."
            echo "triggered=skipped" >> "$GITHUB_OUTPUT"
          else
            echo "Generator workflow is idle. Triggering now..."
            gh api \
              --method POST \
              -H "Accept: application/vnd.github+json" \
              "/repos/${TARGET_OWNER}/${TARGET_REPO}/dispatches" \
              -f '{"event_type":"new_image_available"}'
            echo "Trigger dispatch sent."
            echo "triggered=sent" >> "$GITHUB_OUTPUT"
          fi
      
      # ----- KẾT THÚC THAY ĐỔI -----

      - name: Send Success Message to Telegram
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ✅ KTB Image Crawl - Done.
            Changes detected: ${{ steps.check_changes.outputs.changes_exist }}
            Generator trigger: ${{ steps.trigger_generator.outputs.triggered }}

      - name: Send Failure Message to Telegram
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: "❌ KTB Image Crawl - Fail."
