name: Crawl Image V3

on:
  schedule:
    - cron: "*/20 2-16 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 python-telegram-bot

      - name: Run crawler
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python crawler-image.py

      # Thay đổi ở đây
      - name: Send Log Content to Telegram
        if: always()
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          LOG_CONTENT=$(cat crawl-log.txt)
          curl -s -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage \
          -d chat_id=$TELEGRAM_CHAT_ID \
          -d text="${LOG_CONTENT}" || echo "Lỗi khi gửi nội dung log!"

      - name: Send Success Message to Telegram
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: "✅ KTBihow Crawl ImgV3 - Done."

      - name: Send Failure Message to Telegram
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: "❌ KTBihow Crawl ImgV3 - Fail."

      - name: Commit & push results
        if: success()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add *.txt
          git commit -m "Update URLs [skip ci]" || echo "No changes to commit"
          git push
      - name: Trigger generator workflow
        if: success()
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.CHANKTB_PAT }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/chanktb/ktb-image/dispatches \
          -d '{"event_type":"new_urls_available"}'
          # Command to trigger the second repository on a different account
          curl -X POST \
          -H "Authorization: token ${{ secrets.KTBGIT_PAT }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/ktbgit/ktb-image/dispatches \
          -d '{"event_type":"new_urls_available"}'
          # Command to trigger the 3rd repository on a different account
          curl -X POST \
          -H "Authorization: token ${{ secrets.KTBHUB_PAT }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/ktbhub/ktb/dispatches \
          -d '{"event_type":"new_urls_available"}'
