name: KTB Image Crawler

on:
  repository_dispatch:
    types: [new_product_available]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 python-telegram-bot

      - name: Run crawler
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python crawler-image.py

      - name: Send Log Content to Telegram
        if: always()
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          LOG_CONTENT=$(cat crawl-log.txt)
          TRUNCATED_LOG=$(echo "$LOG_CONTENT" | head -c 4000)
          curl -s -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage \
          -d chat_id=$TELEGRAM_CHAT_ID \
          -d text="${TRUNCATED_LOG}" || echo "Lỗi khi gửi nội dung log!"

      # ----- LOGIC KIỂM TRA ĐÃ ĐƯỢC THAY THẾ -----
      - name: Check for meaningful changes
        id: check_meaningful_changes
        run: |
          echo "Checking for new image URLs in crawl-log.txt..."
          # Điều kiện 1: Kiểm tra xem có URL mới nào được thêm vào trong log không
          has_new_urls_in_log=false
          if grep -E -q '[1-9][0-9]* new URLs added' crawl-log.txt; then
            has_new_urls_in_log=true
            echo "Meaningful changes detected in crawl-log.txt."
          else
            echo "No new URLs found in crawl-log.txt."
          fi

          echo "Checking for direct changes in data files..."
          # Điều kiện 2: Kiểm tra xem có file .txt nào khác ngoài log bị thay đổi không
          has_data_file_changes=false
          # Tìm tất cả các file .txt, loại trừ crawl-log.txt, rồi kiểm tra diff
          other_txt_files=$(find . -maxdepth 1 -type f -name "*.txt" ! -name "crawl-log.txt")
          if [ -n "$other_txt_files" ]; then
            git add $other_txt_files
            if ! git diff --staged --quiet; then
              has_data_file_changes=true
              echo "Meaningful changes detected in data files (e.g., stop url.txt, domain.com.txt)."
            fi
          else
            echo "No other .txt data files found to check."
          fi
          
          # Kết hợp 2 điều kiện: Chỉ kích hoạt khi có URL mới trong log HOẶC có file dữ liệu bị thay đổi
          if [ "$has_new_urls_in_log" = true ] || [ "$has_data_file_changes" = true ]; then
            echo "Meaningful changes exist. Proceeding to commit and trigger."
            echo "changes_exist=true" >> "$GITHUB_OUTPUT"
          else
            echo "No meaningful changes detected. Skipping commit and trigger."
            echo "changes_exist=false" >> "$GITHUB_OUTPUT"
          fi

      # ----- KẾT THÚC THAY ĐỔI LOGIC KIỂM TRA -----

      - name: Commit & push results
        if: success() && steps.check_meaningful_changes.outputs.changes_exist == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          # Chỉ add tất cả các file txt khi thực sự có thay đổi
          git add *.txt
          git commit -m "Update image URLs [skip ci]"
          git push

      - name: Check status and trigger generator workflow
        if: success() && steps.check_meaningful_changes.outputs.changes_exist == 'true'
        id: trigger_generator
        env:
          GH_TOKEN: ${{ secrets.KTBHUB_PAT }}
          TARGET_OWNER: 'ktbhub'
          TARGET_REPO: 'ktb-image'
          TARGET_WORKFLOW: 'auto-generate.yml'
        run: |
          echo "Checking status of '${TARGET_WORKFLOW}' in ${TARGET_OWNER}/${TARGET_REPO}..."

          in_progress_runs=$(gh run list \
            --repo "${TARGET_OWNER}/${TARGET_REPO}" \
            --workflow "${TARGET_WORKFLOW}" \
            --status "in_progress" \
            --status "queued" \
            --limit 1 \
            --json databaseId)

          if [[ "$in_progress_runs" != "[]" ]]; then
            echo "Generator workflow is busy. Skipping trigger."
            echo "triggered=skipped" >> "$GITHUB_OUTPUT"
          else
            echo "Generator workflow is idle. Triggering now..."
            # Sửa lỗi cú pháp -d thành -f cho gh api
            gh api \
              --method POST \
              -H "Accept: application/vnd.github+json" \
              "/repos/${TARGET_OWNER}/${TARGET_REPO}/dispatches" \
              -f event_type='new_image_available'
            echo "Trigger dispatch sent."
            echo "triggered=sent" >> "$GITHUB_OUTPUT"
          fi
      
      - name: Send Success Message to Telegram
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ✅ KTB Image Crawl - Done.
            Meaningful changes: ${{ steps.check_meaningful_changes.outputs.changes_exist }}
            Generator trigger: ${{ steps.trigger_generator.outputs.triggered }}

      - name: Send Failure Message to Telegram
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: "❌ KTB Image Crawl - Fail."
