name: KTB Image Crawler

on:
  repository_dispatch:
    types: [new_product_available]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 python-telegram-bot

      - name: Run crawler
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python crawler-image.py

      # Các bước gửi log Telegram giữ nguyên
      - name: Send Log Content to Telegram
        if: always()
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          LOG_CONTENT=$(cat crawl-log.txt)
          curl -s -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage \
          -d chat_id=$TELEGRAM_CHAT_ID \
          -d text="${LOG_CONTENT}" || echo "Lỗi khi gửi nội dung log!"

      # ----- THAY ĐỔI BẮT ĐẦU TỪ ĐÂY -----

      - name: Check for changes
        id: check_changes # <-- Đặt ID cho bước này để tham chiếu output
        run: |
          git add *.txt
          if ! git diff --staged --quiet; then
            echo "Có thay đổi, tiến hành commit và trigger."
            echo "changes_exist=true" >> "$GITHUB_OUTPUT"
          else
            echo "Không có thay đổi nào."
            echo "changes_exist=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Commit & push results
        # Chỉ chạy khi bước check_changes có output 'changes_exist=true'
        if: success() && steps.check_changes.outputs.changes_exist == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "Update URLs [skip ci]"
          git push

      - name: Trigger generator workflow
        # Chỉ chạy khi bước check_changes có output 'changes_exist=true'
        if: success() && steps.check_changes.outputs.changes_exist == 'true'
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.KTBHUB_PAT }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/ktbhub/ktb-image/dispatches \
          -d '{"event_type":"new_image_available"}'

      # ----- KẾT THÚC THAY ĐỔI -----

      # Các bước gửi tin nhắn thành công/thất bại giữ nguyên
      - name: Send Success Message to Telegram
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: "✅ KTB Image Crawl - Done."

      - name: Send Failure Message to Telegram
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: "❌ KTB Image Crawl - Fail."
